import rawIdl from "./prediction_market.json";
import { PublicKey } from "@solana/web3.js";

const PROGRAM_ID = new PublicKey("7QvFHwKAQQaMsERG6pYLVaeMzac79R18arTpzEc6J7u3");

// ── Why this file exists ────────────────────────────────────────────────
// prediction_market.json is a PRE-0.30 ("legacy") Anchor IDL — generated by
// Solana Playground's bundled toolchain. @coral-xyz/anchor 0.30.1 on the
// frontend expects the NEW IDL spec, which differs in ways that don't fail
// loudly as one single error — they fail one at a time as you fix each:
//
//   1. No top-level `address` field           → "Cannot read properties of
//      (program ID must live in idl.address)    undefined (reading '_bn')"
//   2. `{defined: "Name"}` shorthand for       → "Type not found: <field
//      user types (needs {defined:{name:...}})   name>" (confusing: it
//                                                 names the FIELD, not the
//                                                 missing type)
//   3. Primitive type is `"pubkey"`,           → "Cannot use 'in' operator
//      not the old `"publicKey"`                 to search for 'option' in
//                                                 publicKey"
//   4. Every instruction AND account needs     → "Expected Buffer" /
//      an explicit `discriminator` byte array    "Account not found: X"
//      (old IDLs relied on it being implicit)
//   5. `idl.accounts[i]` is now just a         → "Account not found: X"
//      {name, discriminator} REFERENCE; the      (coder looks for the full
//      actual struct fields must live in          struct under the same
//      `idl.types` under the same name            name in idl.types)
//   6. Each account entry in an instruction's  → NOT an error — this is the
//      account list uses `isMut`/`isSigner`      dangerous one. The client
//      (old), not `writable`/`signer` (new)       silently builds the
//                                                 outer instruction with
//                                                 every account defaulting
//                                                 to writable:false/
//                                                 signer:false, and the
//                                                 transaction still gets
//                                                 built and sent — it just
//                                                 fails on-chain with
//                                                 "Cross-program invocation
//                                                 with unauthorized signer
//                                                 or writable account"
//                                                 (PrivilegeEscalation) the
//                                                 moment the program tries
//                                                 to write to whatever
//                                                 account was silently
//                                                 downgraded. No IDL-load
//                                                 error at all, so it looks
//                                                 like a program bug rather
//                                                 than a client-side one.
//
// This was reverse-engineered by installing @coral-xyz/anchor 0.30.1 in an
// isolated sandbox and testing each fix against the REAL library source
// until `new Program(...)`, every instruction encode, and an account
// decode round-trip all passed — not guessed from a changelog. Discriminators
// below are `sha256("global:"+snake_case_name)[0:8]` for instructions and
// `sha256("account:"+PascalCaseName)[0:8]` for accounts, verified against
// TxLINE's own already-confirmed `validate_stat` discriminator
// ([107,197,232,90,191,136,105,185]) to be certain the formula is exactly
// right before trusting it for our own program.
//
// If you regenerate this IDL with a newer Anchor CLI (0.30+), it will
// already be in the new format and this conversion becomes a no-op-safe
// pass-through (the `defined` values will already be objects, `pubkey`
// will already say `pubkey`, `writable`/`signer` will already be set,
// etc.) — this file doesn't need to change either way, but the
// DISCRIMINATORS map below must be kept in sync with lib.rs if instruction
// or account names ever change.

const INSTRUCTION_DISCRIMINATORS = {
  initializeMarket: [35, 35, 189, 193, 155, 48, 170, 203],
  placeBet: [222, 62, 67, 220, 63, 166, 126, 33],
  settleMarket: [193, 153, 95, 216, 166, 6, 144, 217],
  cancelMarket: [205, 121, 84, 210, 222, 71, 150, 11],
  claimWinnings: [161, 215, 24, 59, 14, 236, 242, 221],
  setFixtureId: [201, 173, 201, 79, 20, 6, 54, 205],
  setEarliestSettleTs: [11, 250, 139, 198, 46, 106, 14, 0],
  closeMarket: [88, 154, 248, 186, 48, 14, 123, 244],
};

const ACCOUNT_DISCRIMINATORS = {
  Market: [219, 190, 213, 55, 0, 227, 198, 154],
  Bet: [147, 23, 35, 59, 15, 75, 155, 32],
};

function convertType(t) {
  if (t === null || t === undefined) return t;
  if (typeof t === "string") return t === "publicKey" ? "pubkey" : t;
  if (typeof t !== "object") return t;
  if ("defined" in t) {
    return typeof t.defined === "string" ? { defined: { name: t.defined } } : t;
  }
  if ("option" in t) return { option: convertType(t.option) };
  if ("vec" in t) return { vec: convertType(t.vec) };
  if ("array" in t) return { array: [convertType(t.array[0]), t.array[1]] };
  return t;
}

function convertFields(fields) {
  return (fields || []).map((f) => ({ ...f, type: convertType(f.type) }));
}

/**
 * Converts one instruction's account-meta list from the legacy
 * `isMut`/`isSigner` field names to the new spec's `writable`/`signer`.
 * Handles nested account groups too (old IDLs can nest under `{accounts:
 * [...]}` for composite account structs), though this program's are flat.
 */
function convertAccountMetas(accounts) {
  return (accounts || []).map((acc) => {
    if (Array.isArray(acc.accounts)) {
      // Nested composite account group — recurse.
      return { ...acc, accounts: convertAccountMetas(acc.accounts) };
    }
    const { isMut, isSigner, ...rest } = acc;
    return {
      ...rest,
      writable: acc.writable ?? isMut ?? false,
      signer: acc.signer ?? isSigner ?? false,
    };
  });
}

function convertTypeDef(def) {
  if (!def || !def.type) return def;
  if (def.type.kind === "struct") {
    return { ...def, type: { ...def.type, fields: convertFields(def.type.fields) } };
  }
  return def;
}

let cached = null;

/**
 * Returns the prediction_market IDL converted to the spec Anchor 0.30.x's
 * JS client actually expects. Computed once and memoized — every call site
 * that builds a `prediction_market` Program instance should import from
 * here instead of the raw JSON directly.
 */
export function getPredictionMarketIdl() {
  if (cached) return cached;

  const idl = rawIdl;
  const existingTypeNames = new Set((idl.types || []).map((t) => t.name));
  const accountTypeDefs = (idl.accounts || []).map(convertTypeDef);

  cached = {
    ...idl,
    address: PROGRAM_ID.toBase58(),
    instructions: (idl.instructions || []).map((ix) => ({
      ...ix,
      discriminator: INSTRUCTION_DISCRIMINATORS[ix.name],
      args: (ix.args || []).map((a) => ({ ...a, type: convertType(a.type) })),
      accounts: convertAccountMetas(ix.accounts),
    })),
    accounts: (idl.accounts || []).map((a) => ({
      name: a.name,
      discriminator: ACCOUNT_DISCRIMINATORS[a.name],
    })),
    types: [
      ...accountTypeDefs.filter((t) => !existingTypeNames.has(t.name)),
      ...(idl.types || []).map(convertTypeDef),
    ],
  };

  return cached;
}

export { PROGRAM_ID };